
name: Test-Basics

on:

  push:
    branches:
     - master

  workflow_dispatch:

jobs:
  my_tasting:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print "Hello message" in testing
      run: echo "Hello world from tasting"
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_tasting]
    steps:
    - name: Print "Hello message" in deploy
      run: echo "Hello world from deploy"
